### PR TITLE
[Do Not Merge] Handle react-test-renderer

### PR DESCRIPTION
**Pull request by johnstonphilip**
This PR makes wpps-scripts able to handle all of the dependencies required for running tests with `react-test-renderer`. 

That means any plugin using wpps-scripts can remove `react-test-renderer` as a dependency in it's package.json files, but the tests will still run.

### CODE REVIEW

**Comment by johnstonphilip** [comment]
See companion PR in Pattern Manager here: 
https://github.com/studiopress/pattern-manager/pull/167

**Comment by johnstonphilip** [comment]
This is not yet ready for review

**Comment by johnstonphilip** [comment]
This might not be worth pursuing at this time. I am going to close it for now.

**Comment by mike-day** [comment]
You are a champion for going down this rabbit hole. I had the tests running successfully on my local but could not get rid of some errors, so I abandoned as well.

**Pull request closed without merging**
